[project]
name = "find-me-a-house"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "folium>=0.20.0",
    "geopandas>=1.1.1",
    "googlemaps>=4.10.0",
    "marimo>=0.14.7",
    "polars>=1.32.0",
    "python-dotenv>=1.1.1",
]
